### ISSUE TITLE
Creating Named Graphs inside migrations

### ISSUE THREAD

**Issue by okal** [protojour/migrado#1]
Hi there, @tangram,

Thanks for putting this together. Have just started using it for a project at work. Is it possible to require the "@arangodb/general-graph" module from inside a migration? I'm having trouble doing that. The idea is to create edges and associated named graphs within the same migration. I'm currently getting the following error:

```shell
Error! 2021-06-24T15:24:56Z [21] ERROR [979b9] JavaScript exception in file 'common/bootstrap/modules.js' at 455,11: ArangoError 3100: cannot locate module
File: arangodb/general-graph
!          throw e;
!          ^
```

This is possible inside `arangosh`, so my naive understanding was that it should be doable in `migrate` as well. Any guidance?

**Comment by okal** [comment]
Not sure what changed, but this is somehow working now. I've split out the graph creation logic into its own migration script, which seems to do the trick.

**Comment by tangram** [comment]
Hi @okal. Thanks for your interest.

Migrations are run through the Arango V8 engine, so there _shouldn't_ really be a difference, but to be honest, I haven't really probed the limits of what's possible or not. The error you were getting seems to come from deep down in the engine internals, and might be hard to debug, since ArangoDB logs as if bytes were a rare and precious thing. Now, it seems this all worked out for you in the end, but if you can provide an example or means to replicate this, I'd be happy to look into it and add test cases. 

I expect to resume development of this project in the next few months, by the way, so expect more features soon.

**Comment by okal** [comment]
Thanks for taking time to respond @tangram. I look forward to the features, and to possibly contributing if that's something you'd be open to.

>  since ArangoDB logs as if bytes were a rare and precious thing.
This made me laugh 😂 Thanks.
